export const ADD_WATCHITEM = 'ADD_WATCHITEM';
export const REMOVE_WATCHITEM = 'REMOVE_WATCHITEM';
export const SET_WATCHLIST = 'SET_WATCHLIST';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADD_WATCHITEM_START = 'ADD_WATCHITEM_START';
export const ADD_WATCHITEM_SUCCESS = 'ADD_WATCHITEM_SUCCESS';
export const ADD_WATCHITEM_FAIL = 'ADD_WATCHITEM_FAIL';

export const REMOVE_WATCHITEM_START = 'REMOVE_WATCHITEM_START';
export const REMOVE_WATCHITEM_SUCCESS = 'REMOVE_WATCHITEM_SUCCESS';
export const REMOVE_WATCHITEM_FAIL = 'REMOVE_WATCHITEM_FAIL';

export const FETCH_WATCHLIST_START = 'FETCH_WATCHLIST_START';
export const FETCH_WATCHLIST_SUCCESS = 'FETCH_WATCHLIST_SUCCESS';
export const FETCH_WATCHLIST_FAIL = 'FETCH_WATCHLIST_FAIL';

export const FETCH_RANDOM_MOVIE_SUCCESS = 'FETCH_RANDOM_MOVIE_SUCCESS';
export const FETCH_RANDOM_MOVIE_FAIL = 'FETCH_RANDOM_MOVIE_FAIL';
export const FETCH_RANDOM_MOVIE = 'FETCH_RANDOM_MOVIE';

export const FETCH_RANDOM_SHOW_SUCCESS = 'FETCH_RANDOM_SHOW_SUCCESS';
export const FETCH_RANDOM_SHOW_FAIL = 'FETCH_RANDOM_SHOW_FAIL';
export const FETCH_RANDOM_SHOW = 'FETCH_RANDOM_SHOW';


export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
export const FETCH_MOVIE_DETAILS_SUCCESS = 'FETCH_MOVIE_DETAILS_SUCCESS';


export const FETCH_NOW_PLAYING_SUCCESS = 'FETCH_NOW_PLAYING_SUCCESS';
export const FETCH_NOW_PLAYING_FAIL = 'FETCH_NOW_PLAYING_FAIL';
export const FETCH_NOW_PLAYING = 'FETCH_NOW_PLAYING';

export const FETCH_UPCOMING_SUCCESS = 'FETCH_UPCOMING_SUCCESS';
export const FETCH_UPCOMING_FAIL = 'FETCH_UPCOMING_FAIL';
export const FETCH_UPCOMING = 'FETCH_UPCOMING';

export const FETCH_VIDEO_KEY = 'FETCH_VIDEO_KEY';
export const FETCH_VIDEO_KEY_SUCCESS = 'FETCH_VIDEO_KEY_SUCCESS';
export const FETCH_VIDEO_KEY_FAIL = 'FETCH_VIDEO_KEY_FAIL';

export const FETCH_TRENDING_TV = 'FETCH_TRENDING_TV';
export const FETCH_TRENDING_TV_SUCCESS = 'FETCH_TRENDING_TV_SUCCESS';
export const FETCH_TRENDING_TV_FAIL = 'FETCH_TRENDING_TV_FAIL';



export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';



