export const ADD_WATCHITEM = 'ADD_WATCHITEM';
export const REMOVE_WATCHITEM = 'REMOVE_WATCHITEM';
export const SET_WATCHLIST = 'SET_WATCHLIST';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADD_WATCHITEM_START = 'ADD_WATCHITEM_START';
export const ADD_WATCHITEM_SUCCESS = 'ADD_WATCHITEM_SUCCESS';
export const ADD_WATCHITEM_FAIL = 'ADD_WATCHITEM_FAIL';

export const FETCH_WATCHLIST_START = 'FETCH_WATCHLIST_START';
export const FETCH_WATCHLIST_SUCCESS = 'FETCH_WATCHLIST_SUCCESS';
export const FETCH_WATCHLIST_FAIL = 'FETCH_WATCHLIST_FAIL';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';



